### PR TITLE
mpn

### PR DESCRIPTION
**Pull request by AssCasc**
Added MPN property in product and combination
Added ISBN property in combination
Added set function in product date_add and date_upd

### CODE REVIEW

**Comment by AssCasc** [comment]
Fix this #432 and this @ #429 issues

**Comment by LorenzoTecnab** [comment]
Dear friends where i can download the compiled version with this changes? Thanks in advance, Lorenzo

**Comment by AssCasc** [comment]
This version is merged, so you can download it just downloading the current version

**Comment by LorenzoTecnab** [comment]
I need to recompile or i find the dll?

**Pull request merged**
