### PR TITLE
Move to core

### PR DESCRIPTION
**Pull request by mktitan**
Thank you for the helpful library. I run on Docker linux machines so I decided to migrate this to core. The two major challenges were:
 - Restsharp. This was solved by using a core compatible port of restsharp https://www.nuget.org/packages/RestSharp.NetCore/
 - Reflection. This was solved by using https://github.com/StefH/ReflectionBridge and a bit of refactoring.

I can't run a test suite for verification since there isn't one, but it seems to be working.

### CODE REVIEW

**Comment by EduLeonPavon** [comment]
Hi @mktitan 
Thank you so much! We are going to test this version in a test environment. If everything goes well, we´ll approve your pull request.
Best regards.

**Comment by mktitan** [comment]
Hi @EduLeonPavon 
Sounds good. I'm looking forward to the result of your tests - also since I'm moving to production with this soon!

One concern I have is that the source for the restsharp core project does not seem to be public - least I can't find it. We could ask the developer to release it. How do you feel about this?

**Comment by mktitan** [comment]
@EduLeonPavon we have discovered some issues with the restsharp netcore port. I have contacted the maintainer of that project who hopefully can provide some feedback and the source code.

Can you share your test env?

**Comment by EduLeonPavon** [comment]
Hello @mktitan 
For the moment, we are not going to release a Prestasharp Core version. Restsharp Core is not an official version and we need to be sure to use a stable version of this dependency in Prestasharp.
I hope you understand.
Regards.

**Comment by mktitan** [comment]
I agree and will close this. If you want to make it easier for people to contribute you should strongly consider releasing whatever testing environment that you have for this library.

**Pull request closed without merging**
