### PR TITLE
Async Task pattern added

### PR DESCRIPTION
**Pull request by pumamood**
Hi, with some minimal change i added async pattern with Task.

let me know your thoughts.

### CODE REVIEW

**Comment by mowcixo** [comment]
Hello @pumamood, thanks for the PR!

We will study it because we want to release another things that refactor some code of your PR first, we will let you know soon!

**Comment by mowcixo** [comment]
Hello @pumamood, the refactors are made. Could you review the conflicts to merge this PR?

**Comment by pumamood** [comment]
Hi @mowcixo everything updated and merged.

**Comment by mowcixo** [comment]
Hello @pumamood, thanks for your efforts. 

I would like to separate functionalities in various PR, using this PR to just focus in async tasks, and the new things you wrote like image functionalities, refactorings etc... in new PRs each one. That would make them easier to review and the commit timeline would be more atomic.

Also, the changes you made in PrestaSharp.csproj should not be shared with the community.

Let me know if you agree :)

**Comment by pumamood** [comment]
yes, it was like that in my first commit but i worked on master branch for my project and i forgot to check it before last commit. I'm going to create a branch for it. let you know

**Pull request closed without merging**
