### PR TITLE
Order messages support

### PR DESCRIPTION
**Pull request by sanctusmob**
This is for getting the orders messages - comments from the customer.
Is tested on PS 1.7. 

You can get the order message like this

````
Dictionary<string, string> filter = new Dictionary<string, string>();
filter.Add("id_order", lngOrderID.ToString());

List<Bukimedia.PrestaSharp.Entities.message> MyOrderMessages = messageLink.GetByFilter(filter, "id_DESC", "1");                
if (MyOrderMessages.Any())
{
	string strMessage = WebUtility.HtmlDecode(MyOrderMessages.First().Message);	
}
````

### CODE REVIEW

**Comment by mowcixo** [comment]
Hello @sanctusmob, thanks for the PR, we are interested in merging it, but could you take a look on the review?

**Comment by sanctusmob** [comment]
> Hello @sanctusmob, thanks for the PR, we are interested in merging it, but could you take a look on the review?

Can you be more specific about the review part? Thank you.

**Comment by mowcixo** [comment]
Of course @sanctusmob, I've made some comments over your code, can you take a look?

**Comment by sanctusmob** [comment]
> Of course @sanctusmob, I've made some comments over your code, can you take a look?

Sorry but i can't see your comments. Where did you make comments?

**Comment by mowcixo** [comment]
> > Of course @sanctusmob, I've made some comments over your code, can you take a look?
> 
> Sorry but i can't see your comments. Where did you make comments?

Sorry @sanctusmob, you were right, I didn't publish the review. Can you see it now?

**Pull request merged**
